server:
  port: 8082

spring:
  application:
    name: payment-web

dubbo:
  provider:
    filter: validation_filter,global_exception_filter
  consumer:
    check: false
    filter: validation_filter
  application:
    name: payment-web
    qos-enable: false
  protocol:
    name: dubbo
    port: 30382
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false




